# Get URL's for S&P 500 Firms

In [1]:
#!pip install requests_html

In [2]:
import pandas as pd
from requests_html import HTMLSession #HTMLSession is how it opens pages
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
session = HTMLSession()
r = session.get(url)

In [3]:
#blunt force
r.html.links #gives you all of the links from the source
            #contians links that are absolute and relative links
r.html.absolute_links #gives you only absolute links

#get the table
#r.html.find('table')
#r.html.find('table')[0] get the first table
#r.html.find('#constituents') returns the table with the constituent id
table = r.html.find('#constituents')[0]
table # prints a list, you want the table. Adding the brackets gives you the table
table.text #gives you just the text
table.html #print html

#blunt force the table
table.absolute_links #extracts all the urls from that specfic table ...but too many, we want only wikipedia
pd.read_html(table.html) #prints the table in text (not what we want)

[    Symbol                         Security SEC filings  \
 0      MMM                       3M Company     reports
 1      ABT              Abbott Laboratories     reports
 2     ABBV                      AbbVie Inc.     reports
 3     ABMD                      ABIOMED Inc     reports
 4      ACN                    Accenture plc     reports
 5     ATVI              Activision Blizzard     reports
 6     ADBE                       Adobe Inc.     reports
 7      AMD       Advanced Micro Devices Inc     reports
 8      AAP               Advance Auto Parts     reports
 9      AES                         AES Corp     reports
 10     AFL                        AFLAC Inc     reports
 11       A         Agilent Technologies Inc     reports
 12     APD     Air Products & Chemicals Inc     reports
 13    AKAM          Akamai Technologies Inc     reports
 14     ALK             Alaska Air Group Inc     reports
 15     ALB                   Albemarle Corp     reports
 16     ARE  Alexandria Real Estate Equities     reports
 17    ALXN          Alexion Pharmaceuticals     reports
 18    ALGN                 Align Technology     reports
 19    ALLE                         Allegion     reports
 20     AGN                    Allergan, plc     reports
 21     ADS            Alliance Data Systems     reports
 22     LNT              Alliant Energy Corp     reports
 23     ALL                    Allstate Corp     reports
 24   GOOGL             Alphabet Inc Class A     reports
 25    GOOG             Alphabet Inc Class C     reports
 26      MO                 Altria Group Inc     reports
 27    AMZN                  Amazon.com Inc.     reports
 28    AMCR                        Amcor plc     reports
 29     AEE                      Ameren Corp     reports
 ..     ...                              ...         ...
 475      V                        Visa Inc.     reports
 476    VNO             Vornado Realty Trust     reports
 477    VMC                 Vulcan Materials     reports
 478    WRB        W. R. Berkley Corporation     reports
 479    WAB               Wabtec Corporation     reports
 480    WMT                          Walmart     reports
 481    WBA         Walgreens Boots Alliance     reports
 482    DIS          The Walt Disney Company     reports
 483     WM            Waste Management Inc.     reports
 484    WAT               Waters Corporation     reports
 485    WEC                 WEC Energy Group     reports
 486    WFC                      Wells Fargo     reports
 487   WELL                   Welltower Inc.     reports
 488    WDC                  Western Digital     reports
 489     WU                 Western Union Co     reports
 490    WRK                         WestRock     reports
 491     WY                     Weyerhaeuser     reports
 492    WHR                  Whirlpool Corp.     reports
 493    WMB                    Williams Cos.     reports
 494   WLTW             Willis Towers Watson     reports
 495   WYNN                 Wynn Resorts Ltd     reports
 496    XEL                  Xcel Energy Inc     reports
 497    XRX                            Xerox     reports
 498   XLNX                           Xilinx     reports
 499    XYL                       Xylem Inc.     reports
 500    YUM                  Yum! Brands Inc     reports
 501   ZBRA               Zebra Technologies     reports
 502    ZBH           Zimmer Biomet Holdings     reports
 503   ZION                    Zions Bancorp     reports
 504    ZTS                           Zoetis     reports

                 GICS Sector                             GICS Sub Industry  \
 0               Industrials                      Industrial Conglomerates
 1               Health Care                         Health Care Equipment
 2               Health Care                               Pharmaceuticals
 3               Health Care                         Health Care Equipment
 4    Information Technology                IT Consulting & Other Services
 5    Communication Services                Interactive Home Entertainment
 6    Information Technology                          Application Software
 7    Information Technology                                Semiconductors
 8    Consumer Discretionary                             Automotive Retail
 9                 Utilities  Independent Power Producers & Energy Traders
 10               Financials                       Life & Health Insurance
 11              Health Care                         Health Care Equipment
 12                Materials                              Industrial Gases
 13   Information Technology            Internet Services & Infrastructure
 14              Industrials                                      Airlines
 15                Materials                           Specialty Chemicals
 16              Real Estate                                  Office REITs
 17              Health Care                                 Biotechnology
 18              Health Care                          Health Care Supplies
 19              Industrials                             Building Products
 20              Health Care                               Pharmaceuticals
 21   Information Technology         Data Processing & Outsourced Services
 22                Utilities                            Electric Utilities
 23               Financials                 Property & Casualty Insurance
 24   Communication Services                  Interactive Media & Services
 25   Communication Services                  Interactive Media & Services
 26         Consumer Staples                                       Tobacco
 27   Consumer Discretionary            Internet & Direct Marketing Retail
 28                Materials                               Paper Packaging
 29                Utilities                               Multi-Utilities
 ..                      ...                                           ...
 475  Information Technology         Data Processing & Outsourced Services
 476             Real Estate                                  Office REITs
 477               Materials                        Construction Materials
 478              Financials                 Property & Casualty Insurance
 479             Industrials         Construction Machinery & Heavy Trucks
 480        Consumer Staples                  Hypermarkets & Super Centers
 481        Consumer Staples                                   Drug Retail
 482  Communication Services                        Movies & Entertainment
 483             Industrials           Environmental & Facilities Services
 484             Health Care                      Health Care Distributors
 485               Utilities                            Electric Utilities
 486              Financials                             Diversified Banks
 487             Real Estate                             Health Care REITs
 488  Information Technology    Technology Hardware, Storage & Peripherals
 489  Information Technology         Data Processing & Outsourced Services
 490               Materials                               Paper Packaging
 491             Real Estate                             Specialized REITs
 492  Consumer Discretionary                          Household Appliances
 493                  Energy            Oil & Gas Storage & Transportation
 494              Financials                             Insurance Brokers
 495  Consumer Discretionary                              Casinos & Gaming
 496               Utilities                               Multi-Utilities
 497  Information Technology    Technology Hardware, Storage & Peripherals
 498  Information Technology                                Semiconductors
 499             Industrials                          Industrial Machinery
 500  Consumer Discretionary                                   Restaurants
 501  Information Technology            Electronic Equipment & Instruments
 502             Health Care                         Health Care Equipment
 503              Financials                                Regional Banks
 504             Health Care                               Pharmaceuticals

                 Headquarters Location Date first added      CIK      Founded
 0                 St. Paul, Minnesota       1976-08-09    66740         1902
 1             North Chicago, Illinois       1964-03-31     1800         1888
 2             North Chicago, Illinois       2012-12-31  1551152  2013 (1888)
 3              Danvers, Massachusetts       2018-05-31   815094         1981
 4                     Dublin, Ireland       2011-07-06  1467373         1989
 5            Santa Monica, California       2015-08-31   718877         2008
 6                San Jose, California       1997-05-05   796343         1982
 7             Santa Clara, California       2017-03-20     2488         1969
 8             Raleigh, North Carolina       2015-07-09  1158449         1932
 9                 Arlington, Virginia       1998-10-02   874761         1981
 10                  Columbus, Georgia       1999-05-28     4977         1955
 11            Santa Clara, California       2000-06-05  1090872         1999
 12            Allentown, Pennsylvania       1985-04-30     2969         1940
 13           Cambridge, Massachusetts       2007-07-12  1086222         1998
 14                Seattle, Washington       2016-05-13   766421         1985
 15          Charlotte, North Carolina       2016-07-01   915913         1994
 16               Pasadena, California       2017-03-20  1035443         1994
 17              Boston, Massachusetts       2012-05-25   899866         1992
 18               San Jose, California       2017-06-19  1097149         1997
 19                    Dublin, Ireland       2013-12-02  1579241         1908
 20                    Dublin, Ireland       1999-04-12  1578845         1983
 21                       Plano, Texas       2013-12-23  1101215         1996
 22                 Madison, Wisconsin       2016-07-01   352541         1917
 23      Northfield Township, Illinois       1995-07-13   899051         1931
 24          Mountain View, California       2014-04-03  1652044         1998
 25          Mountain View, California       2006-04-03  1652044         1998
 26                 Richmond, Virginia              NaN   764180         1985
 27                Seattle, Washington       2005-11-18  1018724         1994
 28   Warmley, Bristol, United Kingdom       2019-06-07  1748790  2019 (1860)
 29                St. Louis, Missouri       1991-09-19  1002910         1902
 ..                                ...              ...      ...          ...
 475         San Francisco, California       2009-12-21  1403161          NaN
 476                New York, New York              NaN   899689         1982
 477               Birmingham, Alabama       1999-06-30  1396009          NaN
 478            Greenwich, Connecticut       2019-12-05    11544         1967
 479          Wilmerding, Pennsylvania       2019-02-27   943452  1999 (1869)
 480             Bentonville, Arkansas       1982-08-31   104169          NaN
 481               Deerfield, Illinois       1979-12-31  1618921         2014
 482               Burbank, California       1976-06-30  1001039          NaN
 483                    Houston, Texas              NaN   823768         1968
 484            Milford, Massachusetts              NaN  1000697         1958
 485              Milwaukee, Wisconsin       2008-10-31   783325          NaN
 486         San Francisco, California       1976-06-30    72971          NaN
 487                      Toledo, Ohio       2009-01-30   766704          NaN
 488                Irvine, California       2009-07-01   106040          NaN
 489               Englewood, Colorado              NaN  1365135         1851
 490                Richmond, Virginia              NaN  1636023         2015
 491           Federal Way, Washington              NaN   106535         1900
 492           Benton Harbor, Michigan              NaN   106640         1911
 493                   Tulsa, Oklahoma       1975-03-31   107263          NaN
 494            London, United Kingdom       2016-01-05  1140536          NaN
 495                  Paradise, Nevada       2008-11-14  1174922          NaN
 496            Minneapolis, Minnesota              NaN    72903         1909
 497              Norwalk, Connecticut              NaN   108772         1906
 498              San Jose, California       1999-11-08   743988          NaN
 499            White Plains, New York       2011-11-01  1524472         2011
 500              Louisville, Kentucky       1997-10-06  1041061          NaN
 501            Lincolnshire, Illinois       2019-12-23   877212         1969
 502                   Warsaw, Indiana       2001-08-07  1136869          NaN
 503              Salt Lake City, Utah       2001-06-22   109380          NaN
 504          Florham Park, New Jersey       2013-06-21  1555280         1952

 [505 rows x 9 columns]]

In [4]:
#let's loop over the rows
table.find('tr') #gives a list of rows
table.find('tr')[0].text #header
table.find('tr')[1].text

table_rows = table.find('tr')

colinks = []
for row in table_rows[1:]:
    a_link = list(row.find('td')[1].absolute_links)[0]
    colinks.append(a_link)
colinks
len(colinks) # they're 505 firms in the S&P500

505

# Lets Clean That Up

In [1]:
import pandas as pd
from requests_html import HTMLSession #HTMLSession is how it opens pages

#open the page
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
session = HTMLSession()
r = session.get(url)

table = r.html.find('#constituents')[0]
table_rows = table.find('tr')

colinks = []
for row in table_rows[1:]:
    a_link = list(row.find('td')[1].absolute_links)[0]
    colinks.append(a_link)